version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - "../AnonByte:/var/www"
      - "../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../docker/nginx/logs:/var/log/nginx"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      # - "traefik.http.routers.nginx.tls=true"
      # - "traefik.http.routers.nginx.tls.certresolver=production"
    networks:
      AnonByte:

  laravel:
    build: ../docker/php
    image: laravel-app
    volumes:
      - ../AnonByte:/app
      - ../AnonByte/tailwind.config.js:/app/tailwind.config.js
      - ../AnonByte/postcss.config.js:/app/postcss.config.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`laravel.localhost`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=8000"
    networks:
      AnonByte2:
        ipv4_address: 11.0.0.3

networks:
  AnonByte2:
    external: true
