version: "3.8"

services:
  # PhPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    environment:
        PMA_ARBITRARY: 1
    networks:
      AnonByte2:

networks:
  AnonByte2:
    external: true
