version: "3.8"
services:
  # MySql
  db:
    image: mysql:8.0
    container_name: Mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - "./Mysql:/var/lib/mysql"
    networks:
      Database:
        ipv4_address: 10.0.0.5

  # PhPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
        PMA_ARBITRARY: 1
    networks:
      Database:
        ipv4_address: 10.0.0.10

networks:
  Database:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
