version: "3.8"

services:
  # Reverse proxy
  traefik:
    image: "traefik:v2.9"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      AnonByte2:
        ipv4_address: 11.0.0.2

networks:
  AnonByte2:
    external: true
