version: "3.8"
services:
  vsftpd:
    image: fauria/vsftpd
    environment:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASSWORD}
    ports:
        - "20:20"
        - "21:21"
    volumes:
        - "./logs:/var/log/vsftpd"
